# Generated by Django 4.2.7 on 2024-03-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PGSProject',
        ),
        migrations.DeleteModel(
            name='PGSProject2',
        ),
        migrations.DeleteModel(
            name='PGSProject3',
        ),
        migrations.DeleteModel(
            name='PGSRoomReserving',
        ),
        migrations.DeleteModel(
            name='PGSRubric',
        ),
    ]
